builds:
    - binary: mediumautopost
      goos:
        - darwin
        - linux
      goarch:
        - amd64
        - arm64
      env:
        - CGO_ENABLED=0
      flags:
        - -mod=vendor

release:
    prerelease: auto

universal_binaries:
    - replace: true

brews:
    -
      name: mediumautopost
      homepage: "https://github.com/askcloudarchitech/mediumautopost"
      tap:
        owner: confetti-cms
        name: homebrew-confetti
      commit_author:
        name: Reindert Vetter
        email: reindertvetter+brew@gmail.com

checksum:
    name_template: 'checksums.txt'