builds:
  - binary: confetti
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
       - -o confetti
#      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: confetti
    homepage: "https://confetti-cms.com"
    tap:
      owner: confetti-cms
      name: confetti
    commit_author:
      name: Reindert Vetter
      email: reindertvetter+brew@gmail.com
    install: |
      main: confetti
      id: confetti
      binary: confetti
      bin.install "confetti"

checksum:
  name_template: 'checksums.txt'