builds:
  - binary: conf
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
#    flags:
#      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: conf
    homepage: "https://confetti-cms.com"
    tap:
      owner: confetti-cms
      name: homebrew-conf
    commit_author:
      name: Reindert Vetter
      email: reindertvetter+brew@gmail.com

checksum:
  name_template: 'checksums.txt'